import express from "express";
import sessionController from "../controllers/sessionController.js";
import verifyAccess from "../middleware/Tokenaccess.js";
import Verifytoken from "../middleware/Tokenverify.js";
const sessionRouter=express.Router();
sessionRouter.post("/save",Verifytoken,verifyAccess("user"), sessionController.saveSession);
sessionRouter.get("/view",sessionController.viewAll);
sessionRouter.get("/:id",Verifytoken,verifyAccess("user"), sessionController.viewOne);
sessionRouter.patch("/:id", Verifytoken,verifyAccess("admin"), sessionController.updateOne);
sessionRouter.delete("/:id",Verifytoken,verifyAccess("admin"), sessionController.deleteOne);
sessionRouter.patch("/:id/statusapp",Verifytoken,verifyAccess("mentor"), sessionController.changeStatusToApproved);
sessionRouter.patch("/:id/statusdec",Verifytoken,verifyAccess("mentor"), sessionController.changeStatusToDecline);
export default sessionRouter;
